/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class compass_CompassProxy */

#ifndef _Included_compass_CompassProxy
#define _Included_compass_CompassProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     compass_CompassProxy
 * Method:    getCompassData
 * Signature: (FF)Lcompass/CompassResult;
 */
JNIEXPORT jobject JNICALL Java_compass_CompassProxy_getCompassData
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
