package shared;

public enum UserCommand {
    EMPTY,
    EXIT,
    LEFT,
    RIGHT,
    LINE,
    START_LISTEN_DISTANCE,
    STOP_LISTEN_DISTANCE,
    START_LISTEN_COLOR,
    STOP_LISTEN_COLOR,
    START_LISTEN_COMPASS,
    STOP_LISTEN_COMPASS
}